# Generated by Django 5.2.4 on 2025-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_percentage', models.PositiveIntegerField(default=50)),
                ('time_limit', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
